"""Self-host the site's web fonts (all SIL Open Font License) so the browser makes no third-party requests.

Downloads the latin + latin-ext woff2 subsets that Google Fonts serves for the exact families/weights the
site uses, writes them to public/fonts/, and generates src/styles/fonts.css. Run once when the font set
changes; the output is committed.
"""
import hashlib
import os
import re
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CSS_URL = ("https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@500;600;700;800&family=Inter:wght@400;500;600;700"
           "&family=JetBrains+Mono:wght@400;500;600&family=Newsreader:opsz,wght@6..72,500;6..72,600&display=swap")
UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36"
SUBSETS = {"latin", "latin-ext"}
OUT = os.path.join(ROOT, "public", "fonts")


def get(url, binary=False):
    with urllib.request.urlopen(urllib.request.Request(url, headers={"User-Agent": UA}), timeout=60) as r:
        d = r.read()
        return d if binary else d.decode("utf-8")


css = get(CSS_URL)
blocks = re.findall(r"/\*\s*([a-z\-]+)\s*\*/\s*(@font-face\s*\{[^}]+\})", css)
os.makedirs(OUT, exist_ok=True)
faces, files = [], {}
for subset, block in blocks:
    if subset not in SUBSETS:
        continue
    fam = re.search(r"font-family:\s*'([^']+)'", block).group(1)
    weight = re.search(r"font-weight:\s*([\d ]+);", block).group(1).strip()
    style = re.search(r"font-style:\s*(\w+);", block).group(1)
    url = re.search(r"src:\s*url\(([^)]+)\)", block).group(1)
    rng = re.search(r"unicode-range:\s*([^;]+);", block).group(1).strip()
    if url not in files:
        data = get(url, binary=True)
        name = f"{fam.lower().replace(' ', '-')}-{subset}-{hashlib.sha256(data).hexdigest()[:10]}.woff2"
        with open(os.path.join(OUT, name), "wb") as f:
            f.write(data)
        files[url] = name
    faces.append(f"@font-face {{ font-family: '{fam}'; font-style: {style}; font-weight: {weight}; font-display: swap; "
                 f"src: url('/fonts/{files[url]}') format('woff2'); unicode-range: {rng}; }}")
with open(os.path.join(ROOT, "src", "styles", "fonts.css"), "w", encoding="utf-8", newline="\n") as f:
    f.write("/* Self-hosted web fonts (SIL Open Font License): Barlow Condensed, Inter, JetBrains Mono, Newsreader.\n"
            "   Generated by scripts/fonts/selfhost_fonts.py — latin + latin-ext subsets. No third-party font requests. */\n")
    f.write("\n".join(faces) + "\n")
print(len(faces), "faces,", len(files), "files")
