// WNBA Newsroom hub — PropBetEdge's own articles first; publisher reports are
// shown only as an attributed "source wire" that feeds the articles.
import { html, render } from '../lib/dom.js';
import { api } from '../data/api.js';
import { pageHead, errorState, skeleton, badge, entityChips } from '../ui/components.js';
import { articleCard, articleList, KIND_LABEL, KIND_ORDER } from '../ui/articles.js';
import { relTime, fmtDateTimeET } from '../lib/format.js';

export const title = (p) => (p.kind ? `${KIND_LABEL[p.kind] || 'News'} · WNBA News` : 'WNBA News');
export const description = () => 'The PropBetEdge WNBA newsroom: in-house, source-grounded WNBA articles on injuries, transactions, performances, previews and market trends — each with a bettor angle and cited evidence.';

export async function mount(root, ctx) {
  const kind = ctx.params.kind || null;
  render(root, html`${pageHead({ eyebrow: 'PBE Newsroom', title: 'WNBA News' })}${skeleton(320)}${skeleton(200, 2)}`);
  const [arts, wire] = await Promise.all([api.articles({ limit: 200, kind: kind || undefined }), api.news({ limit: 20, lane: 'external' })]);
  if (!ctx.isCurrent()) return;
  if (!arts.ok) return render(root, html`${pageHead({ eyebrow: 'PBE Newsroom', title: 'WNBA News' })}${errorState(arts, 'The newsroom')}`);
  const items = arts.data.items;
  const byKind = (k) => items.filter((c) => c.kind === k || (k === 'performance' && c.kind === 'result'));
  // Lead: newest injury or preview with a market, else newest article.
  const lead = !kind ? items.find((c) => c.kind === 'injury') || items[0] : items[0];
  const second = !kind ? items.filter((c) => c.id !== lead?.id).slice(0, 3) : [];

  render(root, html`
    ${pageHead({ eyebrow: 'PBE Newsroom', title: kind ? KIND_LABEL[kind] || 'WNBA News' : 'WNBA News', sub: 'Written in-house by the PropBetEdge newsroom from cited records: ESPN’s injury feed, transactions, box scores and standings, stored sportsbook snapshots, and attributed publisher reports. Every article carries a bettor angle, its counter-case and its evidence.' })}
    <div class="pill-row" style="margin-bottom:18px">
      <a class="pill ${!kind ? 'on' : ''}" href="/news">All</a>
      ${KIND_ORDER.filter((k) => k !== 'result').map((k) => html`<a class="pill ${kind === k ? 'on' : ''}" href="/news/c/${k}">${KIND_LABEL[k]}</a>`)}
    </div>

    ${!items.length ? html`<div class="empty"><h3>Nothing in this lane yet</h3><p>The newsroom publishes only when a record supports a story. Quiet days stay quiet.</p></div>` : ''}

    ${!kind && lead ? html`<section class="news-feature">
      ${articleCard(lead, { lead: true })}
      <div class="grid" style="gap:12px">${second.map((c) => articleCard(c))}</div>
    </section>` : ''}

    <div class="split section">
      <div>
        ${kind
          ? articleList(items)
          : KIND_ORDER.filter((k) => byKind(k).length && k !== 'result').map((k) => html`<section style="margin-bottom:28px">
              <div class="sec-head"><h2 class="sec-title bc">${KIND_LABEL[k]}</h2><a class="sec-link" href="/news/c/${k}">All ${KIND_LABEL[k].toLowerCase()} →</a></div>
              ${articleList(byKind(k).filter((c) => c.id !== lead?.id && !second.some((s) => s.id === c.id)).slice(0, 4))}
            </section>`)}
      </div>
      <aside class="grid" style="gap:16px;align-content:start">
        <section class="card">
          <div class="card-head"><span class="card-title">Source wire</span><span class="note">external · attributed</span></div>
          <div class="card-body">
            <p class="note" style="margin-bottom:10px">Publisher reports the newsroom tracks. We keep the headline and the publisher’s own summary only; the reporting belongs to them.</p>
            ${wire.ok ? wire.data.items.slice(0, 12).map((i) => html`<article class="nitem" style="padding:10px 0">
              <div class="nmeta">${badge('ext', i.source.name)}<span>${relTime(i.published_at)}</span></div>
              <h3 style="font-size:15px"><a href="${i.url}" rel="noopener" target="_blank">${i.headline} <span class="note" aria-hidden="true">↗</span></a></h3>
              <div class="nents">${entityChips(i.entities)}</div>
            </article>`) : html`<p class="note">Source wire unavailable.</p>`}
          </div>
        </section>
        <section class="card card-pad">
          <span class="eyebrow">How we write</span>
          <p class="note" style="margin-top:10px">Every article is generated by PropBetEdge from structured records and passes a publication gate before it goes live: each number must appear in a cited record, the only quotes allowed are a publisher’s own headline with the publisher named, no picks or model claims, and every bettor angle must state what argues against it and what is still unknown. Articles that fail are held, not published.</p>
          <p class="note" style="margin-top:10px">Last newsroom pass ${relTime(arts.meta.last_run_at)} · ${arts.data.total} articles live.</p>
        </section>
      </aside>
    </div>
  `);
}
