#!/usr/bin/env python3
"""Emit an additive migration from an assembled box-score artifact.

    python scripts/wbh/notes_sql.py --assembled assembled.json --out migration.sql \
        --dataset wnba_2024_player_box_scores_v1 [--only-game <game_id> ...]

Third and last step. It only ever writes rows the assembler already validated: extraction, row
arithmetic, roster-scoped identity, canonical game match, points reconciliation against the
canonical team score, and the minutes check. The generated SQL re-asserts the reconciliation inside
the transaction, so the database refuses the load if anything drifted between assembly and apply.

NULL means the source did not print the field; a printed zero is stored as zero. These notes carry
no plus/minus column, so plus_minus is NULL throughout.
"""
from __future__ import annotations

import argparse, collections, json
from pathlib import Path

TRANSFORMATION_VERSION = "wbh_notes_boxscore_v1"

STAT_COLUMNS = [
    "seconds_played", "points", "field_goals_made", "field_goals_attempted",
    "three_pointers_made", "three_pointers_attempted", "free_throws_made", "free_throws_attempted",
    "offensive_rebounds", "defensive_rebounds", "rebounds", "assists", "steals", "blocks",
    "turnovers", "personal_fouls", "plus_minus",
]


def lit(v):
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


def build(assembled, dataset, only_games=None):
    entries = [e for e in assembled["team_games"] if not only_games or e["game_id"] in only_games]
    if not entries:
        raise SystemExit("no validated team-games selected")
    docs = {}
    for e in entries:
        docs.setdefault(e["source_sha256"], {"url": e["source_url"], "layout": e["layout"]})
    player_rows = sum(len(e["rows"]) for e in entries)
    per_game = collections.Counter(e["game_id"] for e in entries)
    two_sided = sum(1 for g, n in per_game.items() if n == 2)
    tiers = json.dumps(dict(collections.Counter(
        r.get("identity_tier") for e in entries for r in e["rows"])))

    out = []
    out.append(f"""-- Women's Basketball History — 2024 player box scores from official team game notes
--
-- Generated by scripts/wbh/notes_sql.py from an assembled artifact. Every row below survived, in
-- order: coordinate-aware extraction with per-cell column assignment, its own points arithmetic
-- (points must equal the made shots), identity resolution inside the club's 2024 roster, canonical
-- game matching, a team-level reconciliation of players' points against the canonical team score,
-- and a minutes-total check against regulation plus recorded overtime. Anything that failed any of
-- those is absent from this file rather than approximated.
--
-- NULL means the source did not print the field. A printed zero is stored as zero. These notes
-- carry no plus/minus column, so plus_minus is NULL throughout.
--
-- Source policy is hash-only, as with every other curation migration here: the PDFs are not
-- retained. Each source document row keeps the URL, the retrieval time, the sha256 of the PDF and
-- the transformation version.
--
-- Contents: {len(entries)} team-games, {player_rows} player rows, {two_sided} games with both clubs.

begin;

do $seed$
declare
  v_run uuid;
  v_now timestamptz := clock_timestamp();
  v_dataset constant text := {lit(dataset)};
  v_existing integer;
  v_rows integer;
  v_games integer;
  v_bad integer;""")
    for i in range(len(docs)):
        out.append(f"  v_doc_{i} uuid;")
    out.append(f"""begin
  perform public.wbh_assert_ingestible('pbe_curation');

  select count(*) into v_existing
    from public.wbh_ingestion_runs where scope->>'dataset' = v_dataset and status = 'ok';
  if v_existing > 0 then return; end if;

  insert into public.wbh_ingestion_runs
    (source_id, adapter_id, adapter_version, transformation_version, mode, as_of, scope)
  values
    ('pbe_curation', 'wbh_notes_boxscore', '1.0.0', {lit(TRANSFORMATION_VERSION)}, 'ingest', v_now,
     jsonb_build_object('dataset', v_dataset, 'edition_id', 'wnba_2024',
                        'team_games', {len(entries)}, 'player_rows', {player_rows},
                        'games_with_both_clubs', {two_sided},
                        'identity_tiers', {lit(tiers)}::jsonb,
                        'fields_never_printed_by_source', jsonb_build_array('plus_minus')))
  returning run_id into v_run;
""")

    doc_var = {}
    for i, (sha, meta) in enumerate(docs.items()):
        doc_var[sha] = f"v_doc_{i}"
        note = (f"Official team game notes, layout {meta['layout']}. Player game-log tables read with "
                f"coordinate-aware extraction; PDF body not retained.")
        out.append(f"""  insert into public.wbh_source_documents
    (source_id, source_record_id, request_url, request_method, retrieved_at, http_status, content_sha256,
     content_type, byte_size, storage_state, transformation_version, notes)
  values
    ('pbe_curation', {lit('team_game_notes_' + sha[:16])}, {lit(meta['url'])}, 'GET', v_now, 200,
     {lit(sha)}, 'application/pdf', null, 'hash_only', {lit(TRANSFORMATION_VERSION)}, {lit(note)})
  returning document_id into {doc_var[sha]};
""")

    cols = ("game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, "
            + ", ".join(STAT_COLUMNS)
            + ", source_document_id, ingestion_run_id, transformation_version, derivation, confidence")
    for e in sorted(entries, key=lambda e: (e["date"], e["team_edition_id"])):
        out.append(f"  -- {e['date']} · {e['game_id']} · {e['team_edition_id']} ({e['side']}) · "
                   f"players {e['points_sum']} pts = canonical {e['canonical_points']} · "
                   f"{e['minutes_sum']} player-minutes")
        for r in e["rows"]:
            vals = [lit(e["game_id"]), lit(r["person_id"]), lit(e["team_edition_id"]),
                    lit(r.get("started")), lit(bool(r.get("did_not_play"))), lit(r.get("dnp_reason"))]
            vals += [lit(r.get(c)) for c in STAT_COLUMNS]
            vals += [doc_var[e["source_sha256"]], "v_run", lit(TRANSFORMATION_VERSION),
                     lit("official_team_game_notes:" + (r.get("identity_tier") or "roster_exact")), "0.95"]
            out.append(f"  insert into public.wbh_player_game_stats ({cols})\n"
                       f"  values ({', '.join(vals)});")
        out.append("")

    out.append(f"""  select count(*) into v_rows
    from public.wbh_player_game_stats s
    join public.wbh_ingestion_runs r on r.run_id = s.ingestion_run_id
   where r.scope->>'dataset' = v_dataset;
  if v_rows <> {player_rows} then
    raise exception 'wbh: expected {player_rows} player rows, wrote %', v_rows using errcode = 'P0001';
  end if;

  -- the load re-proves its own arithmetic: every team-game must equal the canonical team score
  select count(*) into v_bad from (
    select s.game_id, s.team_edition_id, sum(s.points) as pts,
           (select gt.points from public.wbh_game_teams gt
             where gt.game_id = s.game_id and gt.team_edition_id = s.team_edition_id) as canon
      from public.wbh_player_game_stats s
      join public.wbh_ingestion_runs r on r.run_id = s.ingestion_run_id
     where r.scope->>'dataset' = v_dataset and not s.did_not_play
     group by 1, 2
  ) t where t.pts is distinct from t.canon;
  if v_bad <> 0 then
    raise exception 'wbh: % team-games do not reconcile to the canonical score', v_bad using errcode = 'P0001';
  end if;

  if exists (select 1 from public.wbh_player_game_stats s
               join public.wbh_ingestion_runs r on r.run_id = s.ingestion_run_id
              where r.scope->>'dataset' = v_dataset
                and (s.field_goals_made > s.field_goals_attempted
                  or s.three_pointers_made > s.three_pointers_attempted
                  or s.free_throws_made > s.free_throws_attempted)) then
    raise exception 'wbh: a row has made greater than attempted' using errcode = 'P0001';
  end if;

  -- a game becomes box_score complete only when both clubs are present and reconciled; nothing here
  -- claims 'full', which would require play-by-play
  update public.wbh_games g
     set completeness = 'box_score', ingestion_run_id = v_run
   where g.edition_id = 'wnba_2024'
     and g.completeness = 'score_only'
     and (select count(distinct s.team_edition_id) from public.wbh_player_game_stats s
           join public.wbh_ingestion_runs r on r.run_id = s.ingestion_run_id
          where s.game_id = g.game_id and r.scope->>'dataset' = v_dataset) = 2;
  get diagnostics v_games = row_count;

  update public.wbh_ingestion_runs
     set status = 'ok',
         counts = jsonb_build_object('player_rows', v_rows, 'games_upgraded_to_box_score', v_games),
         finished_at = clock_timestamp()
   where run_id = v_run;
end $seed$;

commit;""")
    return "\n".join(out), {"team_games": len(entries), "player_rows": player_rows,
                            "documents": len(docs), "games_with_both_clubs": two_sided}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--assembled", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--dataset", default="wnba_2024_player_box_scores_v1")
    ap.add_argument("--only-game", action="append")
    a = ap.parse_args()
    assembled = json.loads(Path(a.assembled).read_text(encoding="utf-8"))
    sql, stats = build(assembled, a.dataset, set(a.only_game or []) or None)
    Path(a.out).write_text(sql, encoding="utf-8")
    print(json.dumps(stats))


if __name__ == "__main__":
    main()
