-- Women's Basketball History — 2024 player box scores from official team game notes
--
-- Generated by scripts/wbh/notes_sql.py from an assembled artifact. Every row below survived, in
-- order: coordinate-aware extraction with per-cell column assignment, its own points arithmetic
-- (points must equal the made shots), identity resolution inside the club's 2024 roster, canonical
-- game matching, a team-level reconciliation of players' points against the canonical team score,
-- and a minutes-total check against regulation plus recorded overtime. Anything that failed any of
-- those is absent from this file rather than approximated.
--
-- NULL means the source did not print the field. A printed zero is stored as zero. These notes
-- carry no plus/minus column, so plus_minus is NULL throughout.
--
-- Source policy is hash-only, as with every other curation migration here: the PDFs are not
-- retained. Each source document row keeps the URL, the retrieval time, the sha256 of the PDF and
-- the transformation version.
--
-- Contents: 2 team-games, 20 player rows, 1 games with both clubs.

begin;

do $seed$
declare
  v_run uuid;
  v_now timestamptz := clock_timestamp();
  v_dataset constant text := 'wnba_2024_first_box_score_game_v1';
  v_existing integer;
  v_rows integer;
  v_games integer;
  v_bad integer;
  v_doc_0 uuid;
  v_doc_1 uuid;
begin
  perform public.wbh_assert_ingestible('pbe_curation');

  select count(*) into v_existing
    from public.wbh_ingestion_runs where scope->>'dataset' = v_dataset and status = 'ok';
  if v_existing > 0 then return; end if;

  insert into public.wbh_ingestion_runs
    (source_id, adapter_id, adapter_version, transformation_version, mode, as_of, scope)
  values
    ('pbe_curation', 'wbh_notes_boxscore', '1.0.0', 'wbh_notes_boxscore_v1', 'ingest', v_now,
     jsonb_build_object('dataset', v_dataset, 'edition_id', 'wnba_2024',
                        'team_games', 2, 'player_rows', 20,
                        'games_with_both_clubs', 1,
                        'identity_tiers', '{"roster_exact": 19, "roster_name_variant": 1}'::jsonb,
                        'fields_never_printed_by_source', jsonb_build_array('plus_minus')))
  returning run_id into v_run;

  insert into public.wbh_source_documents
    (source_id, source_record_id, request_url, request_method, retrieved_at, http_status, content_sha256,
     content_type, byte_size, storage_state, transformation_version, notes)
  values
    ('pbe_curation', 'team_game_notes_5b1f4a49a17d48e1', 'https://cdn.wnba.com/sites/1611661330/2024/09/Dream-Gamenotes-Game-36-vs.-Minnesota-9.10.pdf', 'GET', v_now, 200,
     '5b1f4a49a17d48e1fc812ee229f4ec0ffc7dca6d578a20d0ec1db6daf458099b', 'application/pdf', null, 'hash_only', 'wbh_notes_boxscore_v1', 'Official team game notes, layout dream_2024. Player game-log tables read with coordinate-aware extraction; PDF body not retained.')
  returning document_id into v_doc_0;

  insert into public.wbh_source_documents
    (source_id, source_record_id, request_url, request_method, retrieved_at, http_status, content_sha256,
     content_type, byte_size, storage_state, transformation_version, notes)
  values
    ('pbe_curation', 'team_game_notes_895897334d12ad03', 'https://cdn.wnba.com/sites/1611661330/2024/07/CHI-GAME-NOTES-7-10-1.pdf', 'GET', v_now, 200,
     '895897334d12ad0394418b28489b57d8c95cd1fb0e0912601ebf2c65e0a91e17', 'application/pdf', null, 'hash_only', 'wbh_notes_boxscore_v1', 'Official team game notes, layout sky_2024. Player game-log tables read with coordinate-aware extraction; PDF body not retained.')
  returning document_id into v_doc_1;

  -- 2024-07-02 · gm_wnba_2024_20240702_atl_at_chi · te_atlanta_dream_2024 (home) · players 77 pts = canonical 77 · 200.0 player-minutes
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240702_atl_at_chi', 'gp_WJJ821K132PB', 'te_atlanta_dream_2024', null, true, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, v_doc_0, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:roster_exact', 0.95);
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240702_atl_at_chi', 'gp_00QAEX307XMS', 'te_atlanta_dream_2024', null, false, null, 692, 2, 1, 5, 0, 3, 0, 0, 1, 0, 1, 2, 0, 0, 1, 0, null, v_doc_0, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:roster_exact', 0.95);
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240702_atl_at_chi', 'gp_FDFRQ0T3BVBE', 'te_atlanta_dream_2024', true, false, null, 2400, 11, 3, 6, 1, 4, 4, 6, 1, 1, 2, 7, 1, 0, 2, 2, null, v_doc_0, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:roster_exact', 0.95);
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240702_atl_at_chi', 'gp_0VCETH42ZJ5N', 'te_atlanta_dream_2024', true, false, null, 2015, 19, 8, 21, 1, 1, 2, 4, 6, 8, 14, 5, 1, 1, 2, 3, null, v_doc_0, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:roster_exact', 0.95);
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240702_atl_at_chi', 'gp_JT3DR5GM3D51', 'te_atlanta_dream_2024', true, false, null, 1176, 5, 2, 5, 1, 4, 0, 0, 0, 3, 3, 3, 1, 0, 2, 3, null, v_doc_0, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:roster_exact', 0.95);
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240702_atl_at_chi', 'gp_RAYFNHCW10Z7', 'te_atlanta_dream_2024', null, true, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, v_doc_0, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:roster_exact', 0.95);
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240702_atl_at_chi', 'gp_51FMYE71XSE7', 'te_atlanta_dream_2024', true, false, null, 2079, 19, 8, 13, 3, 7, 0, 2, 0, 3, 3, 4, 1, 0, 3, 1, null, v_doc_0, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:roster_exact', 0.95);
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240702_atl_at_chi', 'gp_YYV84ZYFN5PT', 'te_atlanta_dream_2024', null, false, null, 817, 4, 1, 4, 0, 0, 2, 2, 1, 5, 6, 3, 2, 0, 2, 3, null, v_doc_0, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:roster_exact', 0.95);
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240702_atl_at_chi', 'gp_D47R92459TNK', 'te_atlanta_dream_2024', null, true, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, v_doc_0, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:roster_exact', 0.95);
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240702_atl_at_chi', 'gp_EJE6QAWS9WNS', 'te_atlanta_dream_2024', true, false, null, 1585, 6, 3, 6, 0, 0, 0, 0, 1, 1, 2, 2, 0, 1, 2, 3, null, v_doc_0, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:roster_exact', 0.95);
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240702_atl_at_chi', 'gp_0X0V8YD19HE6', 'te_atlanta_dream_2024', null, false, null, 1236, 11, 4, 8, 1, 3, 2, 2, 1, 5, 6, 1, 0, 0, 4, 2, null, v_doc_0, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:roster_name_variant', 0.95);
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240702_atl_at_chi', 'gp_JJME03VDFBVB', 'te_atlanta_dream_2024', null, true, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, v_doc_0, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:roster_exact', 0.95);

  -- 2024-07-02 · gm_wnba_2024_20240702_atl_at_chi · te_chicago_sky_2024 (away) · players 85 pts = canonical 85 · 201.0 player-minutes
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240702_atl_at_chi', 'gp_YXRG5F81147F', 'te_chicago_sky_2024', false, false, null, 1440, 9, 3, 5, 1, 1, 2, 3, 0, 1, 1, 2, 1, 0, 2, 2, null, v_doc_1, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:roster_exact', 0.95);
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240702_atl_at_chi', 'gp_MAVZ4A7DN19B', 'te_chicago_sky_2024', true, false, null, 2160, 12, 5, 12, 0, 1, 2, 4, 5, 14, 19, 3, 0, 2, 1, 2, null, v_doc_1, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:roster_exact', 0.95);
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240702_atl_at_chi', 'gp_P7JAH60DBSH3', 'te_chicago_sky_2024', true, false, null, 1740, 26, 11, 16, 0, 0, 4, 5, 0, 0, 0, 4, 2, 0, 0, 4, null, v_doc_1, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:roster_exact', 0.95);
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240702_atl_at_chi', 'gp_585QJ199NH2Y', 'te_chicago_sky_2024', true, false, null, 1620, 8, 3, 9, 0, 0, 2, 2, 5, 5, 10, 1, 0, 1, 1, 3, null, v_doc_1, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:roster_exact', 0.95);
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240702_atl_at_chi', 'gp_ZA878Q7W262Z', 'te_chicago_sky_2024', false, false, null, 1380, 14, 5, 8, 4, 6, 0, 0, 0, 1, 1, 3, 0, 0, 1, 1, null, v_doc_1, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:roster_exact', 0.95);
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240702_atl_at_chi', 'gp_GT3A7XEGE909', 'te_chicago_sky_2024', true, false, null, 1560, 6, 2, 5, 1, 1, 1, 2, 0, 0, 0, 3, 2, 1, 2, 1, null, v_doc_1, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:roster_exact', 0.95);
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240702_atl_at_chi', 'gp_97VGE49KWW11', 'te_chicago_sky_2024', false, false, null, 1020, 6, 2, 7, 0, 1, 2, 2, 0, 0, 0, 0, 0, 0, 1, 3, null, v_doc_1, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:roster_exact', 0.95);
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240702_atl_at_chi', 'gp_RNJR7SR939DA', 'te_chicago_sky_2024', true, false, null, 1140, 4, 2, 8, 0, 4, 0, 0, 0, 3, 3, 4, 1, 0, 2, 1, null, v_doc_1, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:roster_exact', 0.95);

  select count(*) into v_rows
    from public.wbh_player_game_stats s
    join public.wbh_ingestion_runs r on r.run_id = s.ingestion_run_id
   where r.scope->>'dataset' = v_dataset;
  if v_rows <> 20 then
    raise exception 'wbh: expected 20 player rows, wrote %', v_rows using errcode = 'P0001';
  end if;

  -- the load re-proves its own arithmetic: every team-game must equal the canonical team score
  select count(*) into v_bad from (
    select s.game_id, s.team_edition_id, sum(s.points) as pts,
           (select gt.points from public.wbh_game_teams gt
             where gt.game_id = s.game_id and gt.team_edition_id = s.team_edition_id) as canon
      from public.wbh_player_game_stats s
      join public.wbh_ingestion_runs r on r.run_id = s.ingestion_run_id
     where r.scope->>'dataset' = v_dataset and not s.did_not_play
     group by 1, 2
  ) t where t.pts is distinct from t.canon;
  if v_bad <> 0 then
    raise exception 'wbh: % team-games do not reconcile to the canonical score', v_bad using errcode = 'P0001';
  end if;

  if exists (select 1 from public.wbh_player_game_stats s
               join public.wbh_ingestion_runs r on r.run_id = s.ingestion_run_id
              where r.scope->>'dataset' = v_dataset
                and (s.field_goals_made > s.field_goals_attempted
                  or s.three_pointers_made > s.three_pointers_attempted
                  or s.free_throws_made > s.free_throws_attempted)) then
    raise exception 'wbh: a row has made greater than attempted' using errcode = 'P0001';
  end if;

  -- a game becomes box_score complete only when both clubs are present and reconciled; nothing here
  -- claims 'full', which would require play-by-play
  update public.wbh_games g
     set completeness = 'box_score', ingestion_run_id = v_run
   where g.edition_id = 'wnba_2024'
     and g.completeness = 'score_only'
     and (select count(distinct s.team_edition_id) from public.wbh_player_game_stats s
           join public.wbh_ingestion_runs r on r.run_id = s.ingestion_run_id
          where s.game_id = g.game_id and r.scope->>'dataset' = v_dataset) = 2;
  get diagnostics v_games = row_count;

  update public.wbh_ingestion_runs
     set status = 'ok',
         counts = jsonb_build_object('player_rows', v_rows, 'games_upgraded_to_box_score', v_games),
         finished_at = clock_timestamp()
   where run_id = v_run;
end $seed$;

commit;