-- Women's Basketball History — 2024 player box scores from official team game notes
--
-- Generated by scripts/wbh/notes_sql.py from an assembled artifact. Every row below survived, in
-- order: coordinate-aware extraction with per-cell column assignment, its own points arithmetic
-- (points must equal the made shots), identity resolution inside the club's 2024 roster, canonical
-- game matching, a team-level reconciliation of players' points against the canonical team score,
-- and a minutes-total check against regulation plus recorded overtime. Anything that failed any of
-- those is absent from this file rather than approximated.
--
-- NULL means the source did not print the field. A printed zero is stored as zero. These notes
-- carry no plus/minus column, so plus_minus is NULL throughout.
--
-- Source policy is hash-only, as with every other curation migration here: the PDFs are not
-- retained. Each source document row keeps the URL, the retrieval time, the sha256 of the PDF and
-- the transformation version.
--
-- Contents: 2 team-games, 21 player rows, 0 games with both clubs.

begin;

do $seed$
declare
  v_run uuid;
  v_now timestamptz := clock_timestamp();
  v_dataset constant text := 'wnba_2024_box_score_wave3_v1';
  v_existing integer;
  v_rows integer;
  v_games integer;
  v_bad integer;
  v_doc_0 uuid;
  v_doc_1 uuid;
begin
  perform public.wbh_assert_ingestible('pbe_curation');

  select count(*) into v_existing
    from public.wbh_ingestion_runs where scope->>'dataset' = v_dataset and status = 'ok';
  if v_existing > 0 then return; end if;

  insert into public.wbh_ingestion_runs
    (source_id, adapter_id, adapter_version, transformation_version, mode, as_of, scope)
  values
    ('pbe_curation', 'wbh_notes_boxscore', '1.0.0', 'wbh_notes_boxscore_v1', 'ingest', v_now,
     jsonb_build_object('dataset', v_dataset, 'edition_id', 'wnba_2024',
                        'team_games', 2, 'player_rows', 21,
                        'games_with_both_clubs', 0,
                        'identity_tiers', '{"roster_exact": 16, "roster_name_variant": 2, "league_unique_in_club_document": 3}'::jsonb,
                        'fields_never_printed_by_source', jsonb_build_array('plus_minus')))
  returning run_id into v_run;

  insert into public.wbh_source_documents
    (source_id, source_record_id, request_url, request_method, retrieved_at, http_status, content_sha256,
     content_type, byte_size, storage_state, transformation_version, notes)
  values
    ('pbe_curation', 'team_game_notes_095639dbde5b1b32', 'https://www.dropbox.com/scl/fo/tilla8k1d3li00no1zr6m/ALyOttkqEEUea81PGqLRZ-k (Connecticut Sun official 2024 game-notes archive, published on sun.wnba.com/notes) :: 6.4_vs._WAS_Game_9_vs._WAS.pdf', 'GET', v_now, 200,
     '095639dbde5b1b3233f2a978e39fe114002163f20d1eb74323d2c06f03c16b9f', 'application/pdf', null, 'hash_only', 'wbh_notes_boxscore_v1', 'Official team game notes, layout sun_2024. Player game-log tables read with coordinate-aware extraction; PDF body not retained.')
  returning document_id into v_doc_0;

  insert into public.wbh_source_documents
    (source_id, source_record_id, request_url, request_method, retrieved_at, http_status, content_sha256,
     content_type, byte_size, storage_state, transformation_version, notes)
  values
    ('pbe_curation', 'team_game_notes_ffc6d116ba153f38', 'https://www.dropbox.com/scl/fo/tilla8k1d3li00no1zr6m/ALyOttkqEEUea81PGqLRZ-k (Connecticut Sun official 2024 game-notes archive, published on sun.wnba.com/notes) :: 9.8_LAS_Game_35_at_LAS.pdf', 'GET', v_now, 200,
     'ffc6d116ba153f384cfc3782a2246648cf43d387ba2ec4cf44b7c7653a49e3a0', 'application/pdf', null, 'hash_only', 'wbh_notes_boxscore_v1', 'Official team game notes, layout sun_2024. Player game-log tables read with coordinate-aware extraction; PDF body not retained.')
  returning document_id into v_doc_1;

  -- 2024-06-02 · gm_wnba_2024_20240602_con_at_atl · te_connecticut_sun_2024 (away) · players 69 pts = canonical 69 · 198.0 player-minutes
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240602_con_at_atl', 'gp_PF3WRR4TDERN', 'te_connecticut_sun_2024', null, false, null, 1800, 18, 8, 15, 2, 4, 0, 2, 1, 9, 10, 1, 0, 2, 4, 4, null, v_doc_0, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:roster_exact', 0.95);
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240602_con_at_atl', 'gp_K029WZ0A91F4', 'te_connecticut_sun_2024', null, false, null, 1920, 15, 6, 10, 1, 2, 2, 3, 0, 4, 4, 3, 1, 0, 2, 4, null, v_doc_0, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:roster_exact', 0.95);
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240602_con_at_atl', 'gp_FBYS22P4DQTT', 'te_connecticut_sun_2024', null, false, null, 1920, 13, 4, 13, 3, 9, 2, 2, 0, 4, 4, 3, 1, 0, 1, 0, null, v_doc_0, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:roster_exact', 0.95);
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240602_con_at_atl', 'gp_SH819JBJBEPM', 'te_connecticut_sun_2024', null, false, null, 1620, 9, 4, 7, 0, 0, 1, 2, 1, 4, 5, 4, 1, 0, 0, 1, null, v_doc_0, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:roster_exact', 0.95);
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240602_con_at_atl', 'gp_HF17K5SNBGB7', 'te_connecticut_sun_2024', null, false, null, 900, 2, 1, 3, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 2, 1, null, v_doc_0, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:roster_exact', 0.95);
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240602_con_at_atl', 'gp_67P8ZGMDB6AZ', 'te_connecticut_sun_2024', null, false, null, 120, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, null, v_doc_0, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:roster_name_variant', 0.95);
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240602_con_at_atl', 'gp_N5C2BEK1V18J', 'te_connecticut_sun_2024', null, false, null, 720, 2, 1, 2, 0, 0, 0, 0, 2, 4, 6, 0, 0, 1, 0, 4, null, v_doc_0, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:roster_exact', 0.95);
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240602_con_at_atl', 'gp_9T5MP9QMVS5V', 'te_connecticut_sun_2024', null, false, null, 2100, 8, 3, 10, 0, 0, 2, 4, 3, 11, 14, 11, 0, 0, 5, 1, null, v_doc_0, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:roster_exact', 0.95);
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240602_con_at_atl', 'gp_5A62X62V0ZT7', 'te_connecticut_sun_2024', null, false, null, 600, 2, 1, 4, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, null, v_doc_0, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:league_unique_in_club_document', 0.95);
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240602_con_at_atl', 'gp_9T6G78EEZ5WR', 'te_connecticut_sun_2024', null, false, null, 120, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, null, v_doc_0, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:league_unique_in_club_document', 0.95);
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240602_con_at_atl', 'gp_NJCFWCK3D4K6', 'te_connecticut_sun_2024', null, false, null, 60, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, null, v_doc_0, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:league_unique_in_club_document', 0.95);

  -- 2024-08-18 · gm_wnba_2024_20240818_con_at_atl · te_connecticut_sun_2024 (away) · players 70 pts = canonical 70 · 199.0 player-minutes
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240818_con_at_atl', 'gp_MHD0P6N59J2Y', 'te_connecticut_sun_2024', null, true, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, v_doc_1, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:roster_exact', 0.95);
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240818_con_at_atl', 'gp_PF3WRR4TDERN', 'te_connecticut_sun_2024', null, false, null, 1560, 9, 3, 9, 1, 2, 2, 2, 1, 9, 10, 3, 1, 1, 1, 4, null, v_doc_1, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:roster_exact', 0.95);
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240818_con_at_atl', 'gp_066TQW6T52TQ', 'te_connecticut_sun_2024', null, false, null, 900, 3, 1, 2, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 2, null, v_doc_1, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:roster_exact', 0.95);
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240818_con_at_atl', 'gp_K029WZ0A91F4', 'te_connecticut_sun_2024', null, false, null, 1320, 4, 1, 5, 0, 1, 2, 2, 0, 3, 3, 0, 1, 0, 4, 3, null, v_doc_1, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:roster_exact', 0.95);
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240818_con_at_atl', 'gp_FBYS22P4DQTT', 'te_connecticut_sun_2024', null, false, null, 1680, 12, 4, 8, 1, 3, 3, 3, 0, 0, 0, 1, 2, 0, 1, 5, null, v_doc_1, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:roster_exact', 0.95);
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240818_con_at_atl', 'gp_SH819JBJBEPM', 'te_connecticut_sun_2024', null, false, null, 1680, 12, 3, 8, 0, 0, 6, 6, 4, 4, 8, 1, 2, 2, 2, 4, null, v_doc_1, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:roster_exact', 0.95);
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240818_con_at_atl', 'gp_RNJR7SR939DA', 'te_connecticut_sun_2024', null, false, null, 2220, 11, 4, 17, 2, 10, 1, 1, 1, 5, 6, 4, 5, 0, 2, 5, null, v_doc_1, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:roster_exact', 0.95);
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240818_con_at_atl', 'gp_67P8ZGMDB6AZ', 'te_connecticut_sun_2024', null, true, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, v_doc_1, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:roster_name_variant', 0.95);
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240818_con_at_atl', 'gp_N5C2BEK1V18J', 'te_connecticut_sun_2024', null, false, null, 720, 6, 2, 4, 0, 0, 2, 2, 2, 3, 5, 0, 1, 0, 2, 2, null, v_doc_1, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:roster_exact', 0.95);
  insert into public.wbh_player_game_stats (game_id, person_id, team_edition_id, started, did_not_play, dnp_reason, seconds_played, points, field_goals_made, field_goals_attempted, three_pointers_made, three_pointers_attempted, free_throws_made, free_throws_attempted, offensive_rebounds, defensive_rebounds, rebounds, assists, steals, blocks, turnovers, personal_fouls, plus_minus, source_document_id, ingestion_run_id, transformation_version, derivation, confidence)
  values ('gm_wnba_2024_20240818_con_at_atl', 'gp_9T5MP9QMVS5V', 'te_connecticut_sun_2024', null, false, null, 1860, 13, 5, 12, 0, 0, 3, 5, 3, 5, 8, 6, 1, 1, 5, 3, null, v_doc_1, v_run, 'wbh_notes_boxscore_v1', 'official_team_game_notes:roster_exact', 0.95);

  select count(*) into v_rows
    from public.wbh_player_game_stats s
    join public.wbh_ingestion_runs r on r.run_id = s.ingestion_run_id
   where r.scope->>'dataset' = v_dataset;
  if v_rows <> 21 then
    raise exception 'wbh: expected 21 player rows, wrote %', v_rows using errcode = 'P0001';
  end if;

  -- the load re-proves its own arithmetic: every team-game must equal the canonical team score
  select count(*) into v_bad from (
    select s.game_id, s.team_edition_id, sum(s.points) as pts,
           (select gt.points from public.wbh_game_teams gt
             where gt.game_id = s.game_id and gt.team_edition_id = s.team_edition_id) as canon
      from public.wbh_player_game_stats s
      join public.wbh_ingestion_runs r on r.run_id = s.ingestion_run_id
     where r.scope->>'dataset' = v_dataset and not s.did_not_play
     group by 1, 2
  ) t where t.pts is distinct from t.canon;
  if v_bad <> 0 then
    raise exception 'wbh: % team-games do not reconcile to the canonical score', v_bad using errcode = 'P0001';
  end if;

  if exists (select 1 from public.wbh_player_game_stats s
               join public.wbh_ingestion_runs r on r.run_id = s.ingestion_run_id
              where r.scope->>'dataset' = v_dataset
                and (s.field_goals_made > s.field_goals_attempted
                  or s.three_pointers_made > s.three_pointers_attempted
                  or s.free_throws_made > s.free_throws_attempted)) then
    raise exception 'wbh: a row has made greater than attempted' using errcode = 'P0001';
  end if;

  -- a game becomes box_score complete only when both clubs are present and reconciled; nothing here
  -- claims 'full', which would require play-by-play
  update public.wbh_games g
     set completeness = 'box_score', ingestion_run_id = v_run
   where g.edition_id = 'wnba_2024'
     and g.completeness = 'score_only'
     and (select count(distinct s.team_edition_id) from public.wbh_player_game_stats s
           join public.wbh_ingestion_runs r on r.run_id = s.ingestion_run_id
          where s.game_id = g.game_id and r.scope->>'dataset' = v_dataset) = 2;
  get diagnostics v_games = row_count;

  update public.wbh_ingestion_runs
     set status = 'ok',
         counts = jsonb_build_object('player_rows', v_rows, 'games_upgraded_to_box_score', v_games),
         finished_at = clock_timestamp()
   where run_id = v_run;
end $seed$;

commit;